### ISSUE TITLE
[Exercise question] Hinging mode in Adenylate Kinase: No template found for residues

### ISSUE THREAD

**Issue by tesla-cat** [molmod/openmm-tutorial-msbs#2]
- For this exercise:  [Hinging mode in Adenylate Kinase](https://render.githubusercontent.com/view/ipynb?color_mode=light&commit=916dc322a5b963921797e065b26a46de1c21df53&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6f6c6d6f642f6f70656e6d6d2d7475746f7269616c2d6d7362732f393136646333323261356239363339323137393765303635623236613436646531633231646635332f30355f616e616c797369732f30335f616c69676e6d656e745f7072696e636970616c5f636f6d706f6e656e745f616e616c797369732e6970796e62&nwo=molmod%2Fopenmm-tutorial-msbs&path=05_analysis%2F03_alignment_principal_component_analysis.ipynb&repository_id=212255692&repository_type=Repository#6.-Hinging-mode-in-Adenylate-Kinase)

- I tried to run simulation for both the original **2rgx** with `<Topology; 2 chains, 321 residues, 1792 atoms, 1713 bonds>` and the reduced version **2rgx-reduced** with `<Topology; 1 chains, 201 residues, 1606 atoms, 1637 bonds>`

- Both had the error: `No template found for residue`

```python
====================================================================================================
<Topology; 2 chains, 321 residues, 1792 atoms, 1713 bonds>
No template found for residue 203 (GLY).  The set of atoms matches GLY, but the bonds are different.  Perhaps the chain is missing a terminal group?

====================================================================================================
<Topology; 1 chains, 201 residues, 1606 atoms, 1637 bonds>
No template found for residue 201 (ILE).  The set of atoms matches ILE, but the bonds are different.  Perhaps the chain is missing a terminal group?
```

- [The notebook to reproduce is here](https://github.com/tesla-cat/Neuroengineering/blob/master/code/OpenMM/exe1/exe1.ipynb)

can you help me? (I am a physicist and have no knowledge of proteins)

**Comment by tovrstra** [comment]
I've pushed a new commit with various small fixes, including a change of the notebook `03_alignment_principal_component_analysis.ipynb`. Can you test if the instructions in this revised version (after the assignment) work for you? In essence, this type of problems can be solved with [PDBFixer](https://github.com/openmm/pdbfixer).

(The notebooks in 07 are currently broken. I'll fix these another time.)

**Comment by tovrstra** [comment]
@tesla-cat I'm going to close this issue, but if you still have a question about this, feel free to re-open.
