### ISSUE TITLE
VSC setup broken

### ISSUE THREAD

**Issue by jeveki** [molmod/openmm-tutorial-msbs#52]
Setting up the environment on VSC does not work anymore in my case. Following the [instructions](https://github.com/molmod/openmm-tutorial-msbs/blob/main/setup_vsc.md), I can no longer open Jupyter Lab. When clicking the launch button, the session is prepared but is closed before ever opening. From the [output](https://github.com/user-attachments/files/17210114/output.log), it seems that the session `Timed out waiting for Jupyter Lab server to open port 7298!`. I cannot find an immediate solution...

@tovrstra : Can you reproduce this?

Also some settings have changed, meaning that we might have to adapt [setup_vsc.md](https://github.com/molmod/openmm-tutorial-msbs/blob/main/setup_vsc.md).

**Comment by jeveki** [comment]
Works like a charm. I made some minor changes to setup_vsc.md to represent the latest version of the Jupyter lablaunching page.

**Comment by tovrstra** [comment]
Thanks!
